import "dotenv/config";
import { groq } from "@ai-sdk/groq";
import { Agent, Memory, VoltAgent, VoltOpsClient } from "@voltagent/core";
import { LibSQLMemoryAdapter } from "@voltagent/libsql";
import { createPinoLogger } from "@voltagent/logger";
import { honoServer } from "@voltagent/server-hono";
import { commerceTools } from "./tools";
import { commerceWorkflows } from "./workflows/commerce";

// Create a logger instance
const logger = createPinoLogger({
	name: "tarai",
	level: "info",
});

// Initialize database schema before starting
async function initializeApp() {
	try {
		logger.info("Initializing Universal Commerce AI System with InstantDB...");

		// Initialize vector embeddings table in LibSQL (if needed for semantic search)
		const { initializeDatabase } = await import("./db/schema");
		const { commerceDb } = await import("./db");
		await initializeDatabase(commerceDb);
		logger.info(
			"✅ LibSQL database initialized for vector embeddings (for semantic search)",
		);
		logger.info("✅ InstantDB initialized for CRUD operations (real-time sync)");

		// Configure persistent memory (LibSQL / SQLite)
		const memory = new Memory({
			storage: new LibSQLMemoryAdapter({
				url: "file:./.voltagent/memory.db",
				logger: logger.child({ component: "libsql" }),
			}),
		});

		// Commerce AI Agent - Universal Commerce AI System
		const commerceAgent = new Agent({
			name: "commerce-assistant",
			instructions: `You are a universal commerce assistant that helps manage products, services, orders, bookings, and more.

DOMAIN-CLUSTERED TOOLS (Action-Based):
You have access to 9 domain tools with action-based routing:

1. **product** - Manage products and instances (variants, inventory, unique items)
   Actions: search, create, update, getDetails, createInstance, updateInstance, getInstances, checkAvailability

2. **order** - Process orders and track status
   Actions: create, update, getDetails, updateStatus, cancel, getByContributor, getByNode

3. **service** - Book appointments and manage services
   Actions: createService, updateService, createSlots, getAvailableSlots, createBooking, updateBooking, cancelBooking, getBookingDetails

4. **node** - Manage business locations
   Actions: create, update, getDetails, getProducts, getServices, getOrders, search

5. **contributor** - Handle customers, staff, drivers
   Actions: create, update, getDetails, getOrders, getBookings, getTasks

6. **task** - Track workflow tasks
   Actions: create, assign, updateStatus, complete, updateLocation, verifyOTP, getByOrder, getByBooking

7. **transaction** - Process payments
   Actions: create, refund, getHistory, getByContributor, getByNode

8. **search** - Advanced search and discovery
   Actions: products, services, nodes, nearMe, semantic

9. **review** - Customer ratings and feedback
   Actions: create, update, getByTarget, getByContributor, verify, delete

WORKFLOWS (For Complex Operations):
- orderProcessing - Complete order lifecycle with validation, tasks, payment
- serviceBooking - Appointment booking with slot management
- productDiscovery - Intelligent product search with ranking
- taskExecution - Task tracking with location and OTP verification

CRITICAL RULES:
1. **Schema Alignment**: Use correct entity names (nodes, contributors, instances, not providers/users)
2. **Action-Based Routing**: Always specify the "action" parameter when calling tools
3. **Instance Management**: Products use instances for variants, inventory, unique items
4. **Workflows for Complex Ops**: Use workflows for multi-step operations (orders, bookings)
5. **Validate Before Orders**: Always check instance availability before creating orders
6. **IDs are UUIDs**: All entity IDs are UUIDs generated by InstantDB

WORKFLOW:
1. For product search: Use search tool with action "products" or "semantic"
2. For product variants: Create product → create instances for each variant
3. For orders: Validate inventory → use orderProcessing workflow
4. For bookings: Check slots → use serviceBooking workflow
5. For discovery: Use productDiscovery workflow for intelligent ranking

EXAMPLES:
- Create product: product.execute({ action: 'create', nodeid: '...', name: '...', price: 999 })
- Search nearby: search.execute({ action: 'nearMe', lat: 12.97, lng: 77.59, radius: 5 })
- Process order: orderProcessingWorkflow.run({ contributorid: '...', items: [...] })
- Book service: serviceBookingWorkflow.run({ serviceId: '...', date: '2025-12-15' })

Always be helpful, check availability before orders, and use workflows for complex operations.`,
			model: groq("openai/gpt-oss-20b"),
			tools: commerceTools,
			memory,
		});

		// Create and start the VoltAgent
		const voltAgent = new VoltAgent({
			agents: {
				commerce: commerceAgent,
			},
			workflows: {
				orderProcessing: commerceWorkflows.orderProcessing,
				serviceBooking: commerceWorkflows.serviceBooking,
				productDiscovery: commerceWorkflows.productDiscovery,
				taskExecution: commerceWorkflows.taskExecution,
			},
			server: honoServer(),
			logger,
			voltOpsClient: new VoltOpsClient({
				publicKey: process.env.VOLTAGENT_PUBLIC_KEY || "",
				secretKey: process.env.VOLTAGENT_SECRET_KEY || "",
			}),
		});

		logger.info("🎉 Universal Commerce AI System started successfully!");
		logger.info("📦 Loaded 9 domain-clustered tools with 61 actions");
		logger.info("🔄 Loaded 4 automated workflows");
		logger.info("🌐 Server running on http://localhost:3141");
		logger.info("🤖 Commerce agent ready to handle requests");
		logger.info("");
		logger.info("💡 Try these commands:");
		logger.info("   - Create a store");
		logger.info("   - Add products with variants");
		logger.info("   - Search for products near me");
		logger.info("   - Process an order");
		logger.info("   - Book a service appointment");
	} catch (error) {
		logger.error("❌ Failed to initialize application:", error as Error);
		process.exit(1);
	}
}

// Start the application
initializeApp();
